### PR TITLE
Allow passing in the kernel function to `fromJSON()`

### PR DESCRIPTION
**Pull request by harthur**
There's no way to JSON-ify the kernel function used to train an SVM, so `fromJSON()` needs a way to let you specify a kernel function.

This patch adds a second argument to `fromJSON()` which is the kernel function. It also adds a node.js test to the `test` directory.

_Side question_: I really like the `toJSON()/fromJSON()` functions because I can train an SVM, store the trained state in JSON and load it in later in another place. But it looks like it has to store all the training data and labels as well. The problem is I have thousands of pieces of ~1000 dimension data, so storing that isn't ideal.

Is there any way avoid storing the training data and labels? Does the SVM always need the original data when it's predicting?

### CODE REVIEW

**Comment by karpathy** [comment]
Hey Heather, right I didn't look into the JSON parts too closely. I agree we need an argument for the type of kernel. The most common kernel types are Linear and RBF so it's probably best to hard code these. If the user uses a special kernel (which should be rather rare), they will have to tweak the code a bit for their specific use case in toJSON and fromJSON. As for the size of the stored object, For Linear SVM all that needs to be saved are the weights and the bias term, so for D-dimensional data the D+1 numbers (there's already code for getting these out), but we need a new function predictLinear (or something like that) that simply computes yhat = sign(X \* w + b) as the output.  As for the Kernel SVM things are more tricky-- we need to store only the support vectors, not necessarily all of the data. The support vectors are those data points for which alpha is non-zero. There can be many or few of them depending on the exact choice of C.

**Comment by karpathy** [comment]
The way to see this property by the way (the fact that data with alpha = 0 don't matter) is to look into marginOne() function that computes the margin of a data point during test time: f += this.alpha[i] \* this.labels[i] \* this.kernel(inst, this.data[i]); Clearly, when this.alpha[i] = 0, f (the accumulator) is not being changed at all. A clever, efficient implementation would probably explicitly check which data points are support vectors and then skip evaluation of the kernel function for these points. That's a good patch :)

**Comment by harthur** [comment]
Excellent explanation, thanks.

hard-coding was tricky for the RBF because you have to save the sigma as well.

**Comment by karpathy** [comment]
"was tricky" : Did you try to write some of this already? I was going to try myself today but I'm not entirely certain on best practices with JSON-related things and as you mention, what the best way is to handle the parameters for kernels.

**Comment by harthur** [comment]
I did try to just save a 'kernelType' and reconstruct the kernel from that type, but the sigma value is hidden inside the kernel function, so it only worked for the linear kernel.

It might be good to just save the 'kernelType' anyways, and require passing the kernel function to `fromJSON()` (or args to the kernel function constructor) if the type isn't linear, and throw an error if it's not provided. Probably better than the way I did it, it would be good to check that you've got the same type of kernel that you'd used to train it.

**Comment by karpathy** [comment]
How about just storing this information in the SVM class? The way I was going to try this was to have a variable inside SVM class kernelType (0 = custom, 1 = linear, 2 = RBF, for example), as well as rbfSigma. The API of train() function would change so you can do train(X, y, 'linear'), or train(X, y, 'rbf', '0.1'), or finally train(X, y, arbitraryFunction) for training with arbitrary kernel, but with custom kernel the toJSON will throw exception or something. Otherwise the SVM would just save its kernelType as well as rbfSigma in to and from JSON. It's not as pretty but maybe it's more practical? Also if the SVM knows that it is using linear kernel, it should just compute the weights and offset and use that in predictLinear() for speed.

**Comment by harthur** [comment]
Yeah, that sounds better.

**Comment by karpathy** [comment]
OK implemented and made better :)

**Pull request closed without merging**
